### PR TITLE
Create en-US-AllColon3.json

### PR DESCRIPTION
**Pull request by Sebbog1**
Another one with only ":3".

### CODE REVIEW

**Comment by coolGi69** [comment]
This is probably the best thing I've ever seen :3

**Review by coolGi69 — APPROVED** [review]

**Comment by coolGi69** [comment]
Only issue I see is that flux only supports real i18n language names, and this isn't one (similar issue to pirate English). This is limitation of flux, and should probably be fixed on our side.

**Comment by realeatham** [comment]
don't we already have 1 of these?

**Comment by realeatham** [comment]
oh this is each letter not word

**Review by realeatham — APPROVED** [review]

**Comment by realeatham** [comment]
I will merge this in a bit if no one is against it

**Pull request merged**
